[tool.ruff]
line-length = 100

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",    # undocumented
    "DOC",
    "TD001", # invalid todo tag
    "N999",
    "TD002", # missing todo author
    "TD003", # missing todo link
    "PD011", # pandas use of dot values
    "CPY001", # missing copyright
    "E501",  # line too long
    "S311",  # randoomness
    "T201",  # print statement
    "RET504", # return statement
    "ERA001", # raise statement
]
unfixable = [
    "F401", # unused import
    "F841", # unused variable
]

logger-objects = ["src.library.logger.LOGGER"]

[tool.ruff.lint.pylint]
max-args = 6